name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D GitHub contributions calendar
        uses: yassinebridi/profile-3d-contrib@v0.4.0
        with:
          output_path: assets/3d-contrib.svg

      - name: Push to the repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/3d-contrib.svg
          git commit -m "Generate 3D contribution calendar"
          git push
